apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
  namespace: dev-env
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

